/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minesweeper;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author nickb
 */
public class GameBoard extends javax.swing.JFrame {

    /**
     * Creates new form GameBoard
     */
    private int boardSize,minesCount;
    
    public static int N = 8;
    private final GameBoardPanel board;
    
    
    public GameBoard(int boardSize,int minesCount) {
        initComponents();
        this.board = new GameBoardPanel(boardSize,minesCount);
        this.add(this.board,BorderLayout.CENTER);
        this.pack();
        this.setVisible(true);
       
    }

  
   
    
    
 
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game");
        setAlwaysOnTop(true);
        setIconImage(new ImageIcon("Images/mine.png").getImage());
        setMinimumSize(new java.awt.Dimension(50, 50));
        getContentPane().setLayout(new java.awt.BorderLayout(0, 30));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
